### ISSUE TITLE
Volume does not match

### ISSUE THREAD

**Issue by schilling3003** [vervallsweg/cast-web-api#72]
The volume set through cast-web-api or returned on the device status through cast-web-api do NOT match the volume the device says when you verbally ask it the volume or set it verbally.

For example- I use the API to set it to 50 and then say "OK Google! What is the current volume?" it returns "The volume is currently set to 55%". And it does not scale linearly either.

1 returns 1
5=5
6=7
10=11
20=22
40=44
60=66
80=88
81=89
82=90
83=91
84=92
85=94
86=95
87=96
88=97
89=98
90=99
91=100

**Comment by vervallsweg** [comment]
Yes! That's true and is a Google Home/Assistant bug.

When I first discovered this bug months ago, discovered the same behavior in the Google Home App. I just tried it on my Google Home and I encourage you to try it too. So you play some music on your GHome. Then open the Google Home app and set the slider to 50% volume. Now ask the assistant on that Google Home what the volume is and it'll reply with 'the volume is 55%'.

Really blows my mind that Google didn't discover/fix this bug after such a long time. This bug was not present was not present when the GHome was released. Back then the volume was still correct on all devices.

Someone would probably need contact Google to get an explanation or fix for this behavior. Maybe post on the product forum? Maybe others already reported this? Didn't investigate at all, because Google is not obeying their own standard and that's luckily not my job to fix 😂
